version: '3.8'

services:
  kaizen-db:
    image: postgres:latest
    container_name: kaizen-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-kaizen}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-kaizen}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  kaizen-api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-unknown}/${GITHUB_REPOSITORY_NAME:-goalgetter}-backend:latest
    container_name: kaizen-api
    restart: always
    ports:
      - "${API_PORT:-3001}:3001"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@kaizen-db:5432/${POSTGRES_DB:-kaizen}"
      PORT: 3001
      # Add other necessary env vars here
    depends_on:
      kaizen-db:
        condition: service_healthy

  kaizen-app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-unknown}/${GITHUB_REPOSITORY_NAME:-goalgetter}-frontend:latest
    container_name: kaizen-app
    restart: always
    ports:
      - "${WEB_PORT:-8080}:80"
    depends_on:
      - kaizen-api

volumes:
  postgres_data:
